### ISSUE TITLE
Breaking change in DNN 7.0.0? - Error getting List of Stream.

### ISSUE THREAD

**Issue by skarpik** [2sic/app-events-and-courses#4]
DNN v7.0.0, 2SXC v11.4.0, Bootstrap 4 Instant theme (v4.10.0)

I created a new DNN installation and added a page to test the Events and Courses module. I dropped the Events and Courses app onto the page and I get the following error. Tested other 2SXC apps and content on another test page - all works perfectly.

Tested the Events and Courses module with DNN 9.6.2 and it works perfectly. It looks as if there is some breaking change in DNN 7.0.0.

Here is the error message from the DNN 7.0.0 website:

Error: System.Exception: Error getting List of Stream. Stream Name: Events DataSource Name: Query ---> System.Exception: Error getting List of Stream. Stream Name: Events DataSource Name: Query ---> System.Exception: Error getting List of Stream. Stream Name: Default DataSource Name: Paging ---> System.Exception: Error getting List of Stream. Stream Name: Default DataSource Name: CmsBlock ---> System.Exception: Looking up BlockConfiguration failed because ModuleId is null. at ToSic.Sxc.DataSources.CmsBlock.get_BlockConfiguration() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\DataSources\CmsBlock.cs:line 100 at ToSic.Sxc.DataSources.CmsBlock.GetContent() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\DataSources\CmsBlock.cs:line 125 at ToSic.Eav.DataSources.DataStream.ReadUnderlyingList() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 118 --- End of inner exception stack trace --- at ToSic.Eav.DataSources.DataStream.ReadUnderlyingList() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 138 at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 103 at ToSic.Eav.LookUp.LookUpInDataTarget.Get(String key, String format, Boolean& notFound) in C:\Projects\eav-server\ToSic.Eav.DataSources\LookUp\LookUpInDataTarget.cs:line 59 at ToSic.Eav.LookUp.TokenReplace.RetrieveTokenValue(String sourceName, String key, String format) in C:\Projects\eav-server\ToSic.Eav.Core\LookUp\TokenReplace.cs:line 157 at ToSic.Eav.LookUp.TokenReplace.ReplaceTokens(String sourceText, Int32 repeat) in C:\Projects\eav-server\ToSic.Eav.Core\LookUp\TokenReplace.cs:line 120 at ToSic.Eav.LookUp.TokenReplace.ReplaceTokens(String sourceText, Int32 repeat) in C:\Projects\eav-server\ToSic.Eav.Core\LookUp\TokenReplace.cs:line 128 at ToSic.Eav.LookUp.LookUpEngine.LookUp(IDictionary`2 values, Int32 depth) in C:\Projects\eav-server\ToSic.Eav.Core\LookUp\LookUpEngine.cs:line 151 at ToSic.Eav.LookUp.LookUpEngine.LookUp(IDictionary`2 values, IDictionary`2 overrides, Int32 depth) in C:\Projects\eav-server\ToSic.Eav.Core\LookUp\LookUpEngine.cs:line 180 at ToSic.Eav.DataSources.Configuration.DataSourceConfiguration.Parse() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataSources\Configuration\Configuration.cs:line 39 at ToSic.Eav.DataSources.Paging.GetList() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataSources\Paging.cs:line 84 at ToSic.Eav.DataSources.DataStream.ReadUnderlyingList() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 118 --- End of inner exception stack trace --- at ToSic.Eav.DataSources.DataStream.ReadUnderlyingList() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 138 at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 103 at ToSic.Eav.DataSources.DataStream.ReadUnderlyingList() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 118 --- End of inner exception stack trace --- at ToSic.Eav.DataSources.DataStream.ReadUnderlyingList() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 138 at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 103 at ToSic.Eav.DataSources.DataStream.ReadUnderlyingList() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 118 --- End of inner exception stack trace --- at ToSic.Eav.DataSources.DataStream.ReadUnderlyingList() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 138 at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 103 at ToSic.Eav.DataSources.DataStream.GetEnumerator() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 170 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) at System.Linq.GroupedEnumerable`3.GetEnumerator() at ASP._Page_Portals_0_2sxc_Events_and_Courses_5_live__Event_List_cshtml.Execute() in d:\Websites\dnn-9-7-0\Website\Portals\0\2sxc\Events and Courses 5\live\_Event-List.cshtml:line 24 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.Sxc.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\Engines\Razor\RazorEngine.cs:line 84 at ToSic.Sxc.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\Engines\Razor\RazorEngine.cs:line 94 at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Engines\EngineBase.cs:line 147 at ToSic.Sxc.Blocks.BlockBuilder.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 59

**Comment by iJungleboy** [comment]
I assume you mean DNN 9.7, not DNN 7 - correct?

I'm almost certain you have this issue - it's a bug in DNN 9.7 they are still trying to fix https://github.com/dnnsoftware/Dnn.Platform/issues/4003

**Comment by skarpik** [comment]
> I assume you mean DNN 9.7, not DNN 7 - correct?
> 
> I'm almost certain you have this issue - it's a bug in DNN 9.7 they are still trying to fix [dnnsoftware/Dnn.Platform#4003](https://github.com/dnnsoftware/Dnn.Platform/issues/4003)

Yes - DNN 9.7.0 (too many Zoom meetings, my brain has gone soft). And yes, the DNN bug that you reference is likely the problem. The only difference is that my bug occurred with a brand new DNN 9.7.0 installation rather than as a by-product of an upgrade from 9.6.2. Almost certainly the same underlying problem. Thanks for the quick reply.

**Comment by iJungleboy** [comment]
np. best join that thread to ensure it will be fixed before 9.7 is released 👍
